### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by laxman1905** [ritwickdey/ritwickdey.github.io#8]
hello sir

i want to add a new folder inside shared/component/(Product-Details) which has product-details.component.html, product-details.component.ts, product-details.component.css, and one more file but in product-details.component.ts get the following error--->
Angular: Can't resolve all parameters for ProductDetailsComponent in C:/Users/laxmankr/WebstormProjects/organic-shop/src/app/shared/components/product-details/product-details.component.ts: (?, ?, [object Object], [object Object], ?).
sir where i have to add this file please tell me quickly ,

Thanks and regard
LAXMAN KUMAR

**Comment by ritwickdey** [comment]
Product Details? o_O 

This is my Portfolio Website :|
